version: '2'
services:
  asterisk:
    build: .
    entrypoint: asterisk -fvvvvv
    network_mode: host
    #ports:
    #  - "8088:8088"
    #  - "8089:8089"
    #  - "5060:5060/tcp"
    #  - "5060:5060/udp"
    #  - "5061:5061/tcp"
    #  - "5061:5061/udp"
    #  - "10000-10100:10000-10100"
    volumes:
      - ./etc/asterisk:/etc/asterisk
      - ./sounds:/usr/share/asterisk/sounds/gestionair
    # fix until https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836924
      - ./rest-api:/usr/share/asterisk/rest-api